version = 0.1

[default.global.parameters]
stack_name = "hs-netsuite-sandbox-rockytop-reliability"
region = "us-east-1"

[default.build.parameters]
cached = false
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "hs-netsuite-sandbox-rockytop-reliability"
profile = "dev-cetdigit"
disable_rollback = true
image_repositories = []
parameter_overrides = "SecretName=\"hs-netsuite/sandbox/rockytop\" HubSpotDealStageCreateId=\"1208741442\" HubSpotDealStageUpdateId=\"1343333815,1208741443,1359370264,1208741444,1208741445,1208741446,1208741447,1346864770\" HubSpotObjectTypeVenue=\"2-52267420\" HubSpotObjectTypePayment=\"0-101\" HubSpotObjectTypeLineItem=\"0-8\" DealVenueNameProperty=\"venue_name_\" HubSpotVenueNameSearchProperties=\"name\" WebhookObjectIdFilterEnabled=\"false\" WebhookObjectIdFilterValue=\"\" NetSuiteAccountId=\"3763009-sb1\" NetSuiteSubsidiaryId=\"5\""
